### ISSUE TITLE
Plans to support other changelog naming conventions?

### ISSUE THREAD

**Issue by mattmenefee** [MaximeD/gem_updater#44]
I've come across a few different changelog naming conventions that are currently not handled:
- `XXX_CHANGELOG.md`: see [Sass](https://github.com/sass/sass/blob/stable/doc-src/SASS_CHANGELOG.md) (which is also nested in a documentation folder)
- `NEWS.md`: for instance, [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md), [factory_girl](https://github.com/thoughtbot/factory_girl/blob/master/NEWS), [factory_girl_rails](https://github.com/thoughtbot/factory_girl_rails/blob/master/NEWS)
- `GitHub releases`: used by a growing number of maintainers. For instance, the folks behind [Guard](https://github.com/guard/guard/releases) and its related gems, [select2](https://github.com/select2/select2/releases/tag/4.0.0), [sass-rails](https://github.com/rails/sass-rails/releases)

If you'd like, I can keep a tally of the relative popularity of these alternate naming conventions (and others that I come across), and then perhaps if they are widely used, open a pull request to handle them?

Let me know what you think! Thanks!

**Comment by MaximeD** [comment]
Hi you're right, there is a bunch of other locations for changelogs that should be supported.

* `news.md` is just a matter of adding it [here](https://github.com/MaximeD/gem_updater/blob/master/lib/gem_updater/source_page_parser.rb#L73).

* `XXX_CHANGELOG.md` at first glance I would said this means checking not the whole filename but only that it contains the desired string. But since `sass` nests it in another directory, I think this is rare enough to be considered as an edge case. Well that should still be supported, so the best option would be to maintain a list of gems known for not having a standard changelog location and hardcode the correct path. Since this list may tend to grow, I would suggest a dedicated `yml` file that lists gem and corresponding uri. This way [SourcePageParser](https://github.com/MaximeD/gem_updater/blob/master/lib/gem_updater/source_page_parser.rb) could at first look in this file for an explicit location before doing it the traditional way.

* `GitHub releases` YES! It should, definitely, just as it should support gems hosted on bitbucket. I did not have time for it lately, but this is clearly an enhancement to be made.

Thank you for your explicit report, and do not hesitate to open a pull request if you have a way to handle one of those.

**Comment by mattmenefee** [comment]
Awesome, I'll open a pull request for `news.md`. And that makes sense about the sass changelog. Sounds good about `Github releases` - if I get some free time, I'll look into it. Thanks!
